/*
 * Copyright (c) 2016. Codetector (Yaotian Feng)
 */

export const AUTHENTICATION = 'AUTHENTICATION'
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const AUTHENTICATION_VERIFICATION = 'AUTHENTICATION_VERIFICATION'

export const EVENT_LIST_CHANGE = 'EVENT_LIST_CHANGE'
export const EVENT_ACTIVATE = 'EVENT_ACTIVATE'
export const EVENT_DEACTIVATE = 'EVENT_DEACTIVATE'

export const RECENT_LIST_CHANGE = 'RECENT_LIST_CHANGE'
export const RECENT_LIST_ADD = 'RECENT_LIST_ADD'
export const RECENT_LIST_REMOVE = 'RECENT_LIST_REMOVE'
